### ISSUE TITLE
Moving eval into separate proposal level?

### ISSUE THREAD

**Issue by b-strauss** [tomhodgins/element-queries-spec#3]
I really like the proposal, it's incredible! But maybe it would be good to move the `eval` stuff into a separate proposal? I can imagine evaluating js inside css might be a bit controversial.

**Comment by tomhodgins** [comment]
Hi @b-strauss!

I definitely agree that it's the wildest and scariest of all the ideas in the proposal, but if you were to separate `eval("")` from scoped styles it would have no reference point through which to evaluate.

When you do:

```css
@element 'div' {
  eval("console.log('offsetWidth')")
}
```

The JS console see's the `div`'s `offsetWidth`, it's evaluating the JS _from the context of_ the scoped element. If you remove this from this scoped styles and element query spec, having an independent `eval("")` spec for CSS doesn't make any sense since it only works inside `@element` queries.

What could be done is to separate `eval("")` into a new level of the Element Queries spec, like to divide the features currently described and say "there are Element Queries Level 1 and these are Level 2". It would be a tremendous loss to scoped styles if they were implemented in a way that didn't (ever) share the context of the query between CSS and JavaScript!

While this spec is being drafted up, I've already been experimenting with this feature using a plugin for almost 2 years and there are many demos on Codepen you're able to check out to see how `eval("")` can be used.

I've also [responded to another issue recently](https://github.com/eqcss/eqcss/issues/50#issuecomment-278664736), outlining the uses for `eval("")` with plenty of examples of how it comes in handy :D

**Comment by b-strauss** [comment]
I think having a new spec level for eval would be the best solution.

**Comment by tomhodgins** [comment]
Exciting news is happening relating to the spec - I've sent a PR to the ResponsiveImagesCG/container-queries#6 repository with the content from our spec so hopefully the improvements made will be at that location in the future :D
